# CLASSIFICATION

NAIVE BAYES (MULTINOMIAL NAVIE BAYES)


In [15]:
import pandas as pd
import numpy as np
import sklearn

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_iris



In [16]:
irisds=load_iris()
irisds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
irisds.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [20]:
irisds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
irisds.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
df=pd.DataFrame(data=irisds.data,columns=irisds.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [28]:
df['target']=irisds.target

In [29]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [31]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int32
dtype: object

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [33]:
x=df.iloc[:,0:-1]
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [36]:
y=df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)

In [39]:
x_train.shape

(105, 4)

In [40]:
x_test.shape

(45, 4)

In [45]:
mnb=MultinomialNB()

In [46]:
mnb.fit(x_train,y_train)

MultinomialNB()

In [48]:
predmnb=mnb.predict(x_test)
predmnb

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [49]:
print (accuracy_score(y_test,predmnb))

0.9555555555555556


In [50]:
print (confusion_matrix(y_test,predmnb))

[[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]


In [52]:
print (classification_report(y_test,predmnb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [72]:
def irispredict (p):
    p=p.reshape(1,-1)
    predmnb=mnb.predict(p)
    print ('predict value: ',predmnb)
    if predmnb==0:
        print ('Sitosa')
    elif predmnb==1:
        print ('Versiculer')
    elif predmnb==2:
        print ('virginica')
        
    
    

In [73]:
p=np.array([6.1,4.5,1.2,0.6])
irispredict (p)

predict value:  [0]
Sitosa


NAIVE BAYES (GAUSSIAN NAVIE BAYES)

In [53]:
df2=pd.read_csv('cancerfile.csv')

In [54]:
df2

Unnamed: 0  mean radius  mean texture  mean perimeter  mean area  \
0             1        20.57         17.77          132.90     1326.0   
1             2        19.69         21.25          130.00     1203.0   
2             4        20.29         14.34          135.10     1297.0   
3             5        12.45         15.70           82.57      477.1   
4             6        18.25         19.98          119.60     1040.0   
..          ...          ...           ...             ...        ...   
490         560        14.05         27.15           91.38      600.4   
491         563        20.92         25.09          143.00     1347.0   
492         564        21.56         22.39          142.00     1479.0   
493         565        20.13         28.25          131.20     1261.0   
494         566        16.60         28.08          108.30      858.1   

     mean smoothness  mean compactness  mean concavity  mean concave points  \
0            0.08474           0.07864         0.08690              0.07017   
1            0.10960           0.15990         0.19740              0.12790   
2            0.10030           0.13280         0.19800              0.10430   
3            0.12780           0.17000         0.15780              0.08089   
4            0.09463           0.10900         0.11270              0.07400   
..               ...               ...             ...                  ...   
490          0.09929           0.11260         0.04462              0.04304   
491          0.10990           0.22360         0.31740              0.14740   
492          0.11100           0.11590         0.24390              0.13890   
493          0.09780           0.10340         0.14400              0.09791   
494          0.08455           0.10230         0.09251              0.05302   

     mean symmetry  ...  worst texture  worst perimeter  worst area  \
0           0.1812  ...          23.41            158.8      1956.0   
1           0.2069  ...          25.53            152.5      1709.0   
2           0.1809  ...          16.67            152.2      1575.0   
3           0.2087  ...          23.75            103.4       741.6   
4           0.1794  ...          27.66            153.2      1606.0   
..             ...  ...            ...              ...         ...   
490         0.1537  ...          33.17            100.2       706.7   
491         0.2149  ...          29.41            179.1      1819.0   
492         0.1726  ...          26.40            166.1      2027.0   
493         0.1752  ...          38.25            155.0      1731.0   
494         0.1590  ...          34.12            126.7      1124.0   

     worst smoothness  worst compactness  worst concavity  \
0              0.1238             0.1866           0.2416   
1              0.1444             0.4245           0.4504   
2              0.1374             0.2050           0.4000   
3              0.1791             0.5249           0.5355   
4              0.1442             0.2576           0.3784   
..                ...                ...              ...   
490            0.1241             0.2264           0.1326   
491            0.1407             0.4186           0.6599   
492            0.1410             0.2113           0.4107   
493            0.1166             0.1922           0.3215   
494            0.1139             0.3094           0.3403   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.1860          0.2750                  0.08902       0  
1                  0.2430          0.3613                  0.08758       0  
2                  0.1625          0.2364                  0.07678       0  
3                  0.1741          0.3985                  0.12440       0  
4                  0.1932          0.3063                  0.08368       0  
..                    ...             ...                      ...     ...  
490                0.1048          0.2250             

In [56]:
x=df2.iloc[:,0:-1]
x

Unnamed: 0  mean radius  mean texture  mean perimeter  mean area  \
0             1        20.57         17.77          132.90     1326.0   
1             2        19.69         21.25          130.00     1203.0   
2             4        20.29         14.34          135.10     1297.0   
3             5        12.45         15.70           82.57      477.1   
4             6        18.25         19.98          119.60     1040.0   
..          ...          ...           ...             ...        ...   
490         560        14.05         27.15           91.38      600.4   
491         563        20.92         25.09          143.00     1347.0   
492         564        21.56         22.39          142.00     1479.0   
493         565        20.13         28.25          131.20     1261.0   
494         566        16.60         28.08          108.30      858.1   

     mean smoothness  mean compactness  mean concavity  mean concave points  \
0            0.08474           0.07864         0.08690              0.07017   
1            0.10960           0.15990         0.19740              0.12790   
2            0.10030           0.13280         0.19800              0.10430   
3            0.12780           0.17000         0.15780              0.08089   
4            0.09463           0.10900         0.11270              0.07400   
..               ...               ...             ...                  ...   
490          0.09929           0.11260         0.04462              0.04304   
491          0.10990           0.22360         0.31740              0.14740   
492          0.11100           0.11590         0.24390              0.13890   
493          0.09780           0.10340         0.14400              0.09791   
494          0.08455           0.10230         0.09251              0.05302   

     mean symmetry  ...  worst radius  worst texture  worst perimeter  \
0           0.1812  ...         24.99          23.41            158.8   
1           0.2069  ...         23.57          25.53            152.5   
2           0.1809  ...         22.54          16.67            152.2   
3           0.2087  ...         15.47          23.75            103.4   
4           0.1794  ...         22.88          27.66            153.2   
..             ...  ...           ...            ...              ...   
490         0.1537  ...         15.30          33.17            100.2   
491         0.2149  ...         24.29          29.41            179.1   
492         0.1726  ...         25.45          26.40            166.1   
493         0.1752  ...         23.69          38.25            155.0   
494         0.1590  ...         18.98          34.12            126.7   

     worst area  worst smoothness  worst compactness  worst concavity  \
0        1956.0            0.1238             0.1866           0.2416   
1        1709.0            0.1444             0.4245           0.4504   
2        1575.0            0.1374             0.2050           0.4000   
3         741.6            0.1791             0.5249           0.5355   
4        1606.0            0.1442             0.2576           0.3784   
..          ...               ...                ...              ...   
490       706.7            0.1241             0.2264           0.1326   
491      1819.0            0.1407             0.4186           0.6599   
492      2027.0            0.1410             0.2113           0.4107   
493      1731.0            0.1166             0.1922           0.3215   
494      1124.0            0.1139             0.3094           0.3403   

     worst concave points  worst symmetry  worst fractal dimension  
0                  0.1860          0.2750                  0.08902  
1                  0.2430          0.3613                  0.08758  
2                  0.1625          0.2364                  0.07678  
3                  0.1741          0.3985                  0.12440  
4                  0.1932          0.3063                  0.08368  
..         

In [57]:
y=df2.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
490    1
491    0
492    0
493    0
494    0
Name: target, Length: 495, dtype: int64

In [59]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)

In [62]:
from sklearn.naive_bayes import GaussianNB

In [63]:
gnb = GaussianNB()

In [64]:
gnb.fit(x_train,y_train)

GaussianNB()

In [65]:
predgnb=gnb.predict(x_test)
predgnb

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [66]:
print (accuracy_score(y_test,predgnb))
print (confusion_matrix(y_test,predgnb))
print (classification_report(y_test,predgnb))

0.959731543624161
[[54  2]
 [ 4 89]]
              precision    recall  f1-score   support

           0       0.93      0.96      0.95        56
           1       0.98      0.96      0.97        93

    accuracy                           0.96       149
   macro avg       0.95      0.96      0.96       149
weighted avg       0.96      0.96      0.96       149

