In [2]:
ds=load_iris()
ds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
print (ds.data)
print (ds.feature_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
ds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
df=pd.DataFrame (ds.data,columns=ds.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df['target']=ds.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [7]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)

In [8]:
mnb= MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
print ('Model Score: ', mnb.score(x_train,y_train))
print ('Accuracy Score:',accuracy_score(y_test,predmnb))
print (confusion_matrix(y_test,predmnb))
print ('Classification Report:', classification_report(y_test,predmnb))




Model Score:  0.95
Accuracy Score: 0.9
[[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [9]:
svm= SVC()
svm.fit(x_train,y_train)
predsvm=svm.predict(x_test)
print ('Model Score: ', svm.score(x_train,y_train))
print ('Accuracy Score:',accuracy_score(y_test,predsvm))
print (confusion_matrix(y_test,predsvm))
print ('Classification Report:', classification_report(y_test,predsvm))

Model Score:  0.975
Accuracy Score: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [10]:
dtc= DecisionTreeClassifier()
dtc.fit(x_train,y_train)
preddtc=dtc.predict(x_test)
print ('Model Score: ', dtc.score(x_train,y_train))
print ('Accuracy Score:',accuracy_score(y_test,preddtc))
print (confusion_matrix(y_test,preddtc))
print ('Classification Report:', classification_report(y_test,preddtc))

Model Score:  1.0
Accuracy Score: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [11]:
knn= KNeighborsClassifier()
knn.fit(x_train,y_train)
predknn=knn.predict(x_test)
print ('Model Score: ', knn.score(x_train,y_train))
print ('Accuracy Score:',accuracy_score(y_test,predknn))
print (confusion_matrix(y_test,predknn))
print ('Classification Report:', classification_report(y_test,predknn))

Model Score:  0.9666666666666667
Accuracy Score: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [12]:
def svmkernel (ker):
    svm=SVC(kernel=ker)
    svm.fit(x_train,y_train)
    svm.score(x_train,y_train)
    predsvm=svm.predict(x_test)
    print (accuracy_score(y_test,predsvm))
    print (confusion_matrix(y_test,predsvm))
    print (classification_report(y_test,predsvm))
    
svmkernel ('rbf')   

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [13]:
svmkernel ('poly')

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [14]:
svmkernel ('linear')

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Cross-validation

In [15]:
from sklearn.model_selection import cross_val_score #k-fold cross valiation

In [16]:
score=cross_val_score(mnb,x,y,cv=5)
print (score)
print (score.mean())
print (score.std())

[1.         0.96666667 0.9        0.9        1.        ]
0.9533333333333334
0.04521553322083511


In [17]:
score=cross_val_score(svm,x,y,cv=7)
print (score)
print (score.mean())
print (score.std())

[0.95454545 1.         1.         0.95238095 0.95238095 0.95238095
 1.        ]
0.9730983302411874
0.023308299993868603


In [18]:
score=cross_val_score(knn,x,y,cv=7)
print (score)
print (score.mean())
print (score.std())


[0.95454545 1.         0.95454545 0.9047619  0.95238095 1.
 1.        ]
0.9666048237476809
0.033087406553853886


In [19]:
model=[mnb,knn,svm,dtc]
def predict(t):
    t=t.reshape(1,-1)
    for i in model:
        pred=i.predict(t)
        print ('Predict Value:', pred)
        if pred==0:
            print ('setosa')
        elif pred==1:
            print ('versicolor')
        elif pred==2:
            print ('virginica')
            

In [20]:
t=np.array([2.1,5.5,0.4,3.2])
predict(t)


Predict Value: [1]
versicolor
Predict Value: [0]
setosa
Predict Value: [0]
setosa
Predict Value: [2]
virginica


# Saving The Best Model

In [21]:
import joblib

In [22]:
joblib.dump(knn,'knnfile.obj') #save the file

['knnfile.obj']

In [23]:
knn_predict_model=joblib.load('knnfile.obj') #reuse the trained model
knn_predict_model


KNeighborsClassifier()

In [24]:
knn_predict_model.predict(x_test) #confirm to check model is working good

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

# SMOTE LIBRARY

In [25]:
df1=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset1/master/pima_indian_diabetes.csv',header=0,names=range(0,8))
df1

0   1   2    3     4      5   6  7
1    85  66  29    0  26.6  0.351  31  0
8   183  64   0    0  23.3  0.672  32  1
1    89  66  23   94  28.1  0.167  21  0
0   137  40  35  168  43.1  2.288  33  1
5   116  74   0    0  25.6  0.201  30  0
..  ...  ..  ..  ...   ...    ...  .. ..
10  101  76  48  180  32.9  0.171  63  0
2   122  70  27    0  36.8  0.340  27  0
5   121  72  23  112  26.2  0.245  30  0
1   126  60   0    0  30.1  0.349  47  1
1    93  70  31    0  30.4  0.315  23  0

[767 rows x 8 columns]

In [26]:
df=pd.DataFrame(data=df1)
df

0   1   2    3     4      5   6  7
1    85  66  29    0  26.6  0.351  31  0
8   183  64   0    0  23.3  0.672  32  1
1    89  66  23   94  28.1  0.167  21  0
0   137  40  35  168  43.1  2.288  33  1
5   116  74   0    0  25.6  0.201  30  0
..  ...  ..  ..  ...   ...    ...  .. ..
10  101  76  48  180  32.9  0.171  63  0
2   122  70  27    0  36.8  0.340  27  0
5   121  72  23  112  26.2  0.245  30  0
1   126  60   0    0  30.1  0.349  47  1
1    93  70  31    0  30.4  0.315  23  0

[767 rows x 8 columns]

In [27]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]
print (x,y)

      0   1   2    3     4      5   6
1    85  66  29    0  26.6  0.351  31
8   183  64   0    0  23.3  0.672  32
1    89  66  23   94  28.1  0.167  21
0   137  40  35  168  43.1  2.288  33
5   116  74   0    0  25.6  0.201  30
..  ...  ..  ..  ...   ...    ...  ..
10  101  76  48  180  32.9  0.171  63
2   122  70  27    0  36.8  0.340  27
5   121  72  23  112  26.2  0.245  30
1   126  60   0    0  30.1  0.349  47
1    93  70  31    0  30.4  0.315  23

[767 rows x 7 columns] 1     0
8     1
1     0
0     1
5     0
     ..
10    0
2     0
5     0
1     1
1     0
Name: 7, Length: 767, dtype: int64


In [28]:
y.value_counts() #unbalanced dataset

0    500
1    267
Name: 7, dtype: int64

# Applying SMOTE:

In [29]:
sklearn.__version__

'1.1.3'

In [30]:
import numpy
numpy.__version__

'1.23.5'

# !pip install imblearn -- user

pip install imblearn

!pip install imblearn

In [31]:
from imblearn.over_sampling import SMOTE

In [32]:
smt=SMOTE()

In [33]:
x_train,y_train=smt.fit_resample(x,y)

In [34]:
x_train.value_counts()

0    1   2   3    4          5         6 
0    48  20  0    24.700000  0.140000  22    1
138  76  0   0    33.200000  0.420000  35    1
137  40  35  168  43.100000  2.288000  33    1
     61  0   0    24.200000  0.151000  55    1
     68  14  148  24.800000  0.143000  21    1
                                            ..
109  76  39  114  27.900000  0.640000  31    1
     80  31  0    35.900000  1.127000  43    1
     86  36  117  42.966616  0.388783  26    1
     88  30  0    32.500000  0.855000  38    1
199  76  43  0    42.900000  1.394000  22    1
Length: 1000, dtype: int64

In [35]:
y_train.value_counts() #Balanced Dataset

0    500
1    500
Name: 7, dtype: int64

In [36]:
irisds=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset1/master/iris.csv')
irisds

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [37]:
irisds['class'].value_counts() #Balanced Dataset

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: class, dtype: int64

# IMBALANCED DATASET

In [38]:
winedf=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset1/master/winequality-red.csv')
winedf

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [39]:
winedf['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [40]:
x=winedf.iloc[:,0:-1]
y=winedf.iloc[:,-1]


In [41]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [42]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [43]:
from imblearn.over_sampling import SMOTE

In [44]:
sm=SMOTE()
x_train,y_train=sm.fit_resample(x,y)

In [45]:
y_train

0       5
1       5
2       5
3       6
4       5
       ..
4081    8
4082    8
4083    8
4084    8
4085    8
Name: quality, Length: 4086, dtype: int64

In [46]:
y_train.value_counts()

5    681
6    681
7    681
4    681
8    681
3    681
Name: quality, dtype: int64

# Principal component analysis (PCA)

In [48]:
from sklearn.decomposition import PCA

In [55]:
data=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/sonar.csv',header=0,names=range(0,61))
data

0       1       2       3       4       5       6       7       8   \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0052  0.0044   R  
1    0.0095  0.0078   R  
2    0.0040  0.0117   R  
3    0.0107  0.0094   R  
4    0.0051  0.0062   R  
..      ...     ...  ..  
202  0.0193  0.0157   M  
203  0.0062  0.0067   M  
204  0.0077  0.0031   M  
205  0.0036  0.0048   M  
206  0.0061  0.0115   M  

[207 rows x 61 columns]

In [56]:
data=pd.DataFrame(data)

data

0       1       2       3       4       5       6       7       8   \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0052  0.0044   R  
1    0.0095  0.0078   R  
2    0.0040  0.0117   R  
3    0.0107  0.0094   R  
4    0.0051  0.0062   R  
..      ...     ...  ..  
202  0.0193  0.0157   M  
203  0.0062  0.0067   M  
204  0.0077  0.0031   M  
205  0.0036  0.0048   M  
206  0.0061  0.0115   M  

[207 rows x 61 columns]

In [57]:
x=data.iloc[:,0:-1]
y=data.iloc[:,-1]

In [58]:
x.shape

(207, 60)

In [59]:
y.shape

(207,)

In [60]:
pca=PCA(n_components=10)
x=pca.fit_transform(x)
x.shape

(207, 10)

In [63]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0   -0.970285  1.017654  0.830432  0.120147  0.299120  0.202682 -0.226988   
1   -0.324435  0.876876  0.228203  0.868926  0.098053 -0.269122 -0.421778   
2    0.853571  0.697734 -0.023602 -0.123425 -0.584388  0.351808  0.478187   
3   -0.061337  0.226034  0.635198  0.152907  0.150982  0.081111 -0.374523   
4   -0.605423  0.901962  0.804550  0.271896  0.496832  0.464410 -0.224909   
..        ...       ...       ...       ...       ...       ...       ...   
202  0.049918 -1.028980  0.265634  0.026018 -0.014738  0.097506  0.012021   
203  0.228374 -1.149870  0.200437  0.043461  0.182020  0.010158  0.084858   
204  0.306763 -1.147756  0.248975 -0.058557  0.161337  0.013778  0.049391   
205 -0.038083 -0.994049  0.201938 -0.060790 -0.147673 -0.088874  0.018656   
206 -0.043904 -0.910802  0.009169 -0.045577 -0.030723 -0.033778  0.025213   

            7         8         9  
0    0.384837  0.004329 -0.082679  
1    0.081072  0.014185 -0.432334  
2   -0.215424 -0.533955 -0.425182  
3    0.070143  0.119454 -0.427480  
4    0.105504 -0.202842 -0.235048  
..        ...       ...       ...  
202  0.178998  0.029362 -0.268631  
203  0.266152 -0.068963 -0.307679  
204  0.227866 -0.070132 -0.313294  
205  0.069504 -0.024406 -0.165303  
206 -0.019100  0.120130 -0.137964  

[207 rows x 10 columns]

In [66]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
y=la.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])