# NUMPAY

In [2]:
import numpy as np

In [2]:
np.array ([1,2,3])

array([1, 2, 3])

In [6]:
a=np.array([10,20,30,40,50])

In [8]:
a

array([10, 20, 30, 40, 50])

In [7]:
a.size

5

In [9]:
a[2]

30

In [12]:
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.min()


10

In [15]:
a.max()

50

In [17]:
p=np.array([[1,2],[3,4]])

In [18]:
  p

array([[1, 2],
       [3, 4]])

In [19]:
p.shape

(2, 2)

In [21]:
s= np.array([[100,200],[300,400]])

In [22]:
s

array([[100, 200],
       [300, 400]])

In [24]:
j=np.array([[24,23],[56,12],[18,57]])

In [25]:
j

array([[24, 23],
       [56, 12],
       [18, 57]])

In [29]:
 j.shape

(3, 2)

In [30]:
j.reshape(2,3)

array([[24, 23, 56],
       [12, 18, 57]])

In [3]:
import numpy as np

In [18]:
e=np.arange(10)

print (e)

k=0

val =int (input ("Enter the value for search"))

for i in e:
    if i==val:
        print (k)
        
        break
        
    k+=1

[0 1 2 3 4 5 6 7 8 9]
Enter the value for search6
6


In [27]:
from numpy import*

arr=np.array([1,2,3,4,5])

arr=arr+5

print (arr)


[ 6  7  8  9 10]


In [28]:
print (cos(arr))

[ 0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [29]:
print (sin(arr))

[-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


In [30]:
print (log(arr))

[1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


In [34]:
arr1=array([2,6,7,8,9])

arr2 =arr1

In [36]:
print (arr2)
print (arr1)

[2 6 7 8 9]
[2 6 7 8 9]


In [39]:
#shallow Copy

arr2=arr1.view()

arr1 [2]=10

print (arr1)
print (arr2)

[ 2  6 10  8  9]
[ 2  6 10  8  9]


In [41]:
#Deep Copy

arr1=arr2.copy()

arr1 [1]=12

print (arr1)
print (arr2)

[ 2 12 10  8  9]
[ 2  6 10  8  9]


In [33]:
np.arange (15).reshape (3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])



In [35]:
a+b

array([5, 7, 9])

In [36]:
a*b

array([ 4, 10, 18])

In [37]:
c=np.array([4])

In [39]:
d=a*c

In [40]:
d

array([ 4,  8, 12])

# ARRAY

In [5]:
import array as arr
    

In [19]:
from array import*

arr=array('i', [])
n=int(input("Enter the length of the array"))
for ai in range (n):
    x=int(input("Enter the next Value"))
    arr.append (x)
    
    
    
    
print(arr) 

#using loop to find index value

val=int(input("Enter the value for search"))

k=0

for i in arr:
    if i ==val:
        print (k)
        
        break
    k+=1
    
#using function to find index value 

print (arr.index(val))
        

Enter the length of the array4
Enter the next Value16
Enter the next Value45
Enter the next Value98
Enter the next Value75
array('i', [16, 45, 98, 75])
Enter the value for search98
2
2
