# Scaling Techniques

2 Types of scaling techinique
1. -- Standard scaling
2. -- MinMax scaling

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_boston
boston=load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
bs=pd.DataFrame(boston.data,columns=boston.feature_names)
bs

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [4]:
bs['target']=boston.target

In [5]:
bs

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [6]:
from scipy.stats import zscore
z=np.abs(zscore(bs))
z

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0    0.419782  0.284830  1.287909  0.272599  0.144217  0.413672  0.120013   
1    0.417339  0.487722  0.593381  0.272599  0.740262  0.194274  0.367166   
2    0.417342  0.487722  0.593381  0.272599  0.740262  1.282714  0.265812   
3    0.416750  0.487722  1.306878  0.272599  0.835284  1.016303  0.809889   
4    0.412482  0.487722  1.306878  0.272599  0.835284  1.228577  0.511180   
..        ...       ...       ...       ...       ...       ...       ...   
501  0.413229  0.487722  0.115738  0.272599  0.158124  0.439316  0.018673   
502  0.415249  0.487722  0.115738  0.272599  0.158124  0.234548  0.288933   
503  0.413447  0.487722  0.115738  0.272599  0.158124  0.984960  0.797449   
504  0.407764  0.487722  0.115738  0.272599  0.158124  0.725672  0.736996   
505  0.415000  0.487722  0.115738  0.272599  0.158124  0.362767  0.434732   

          DIS       RAD       TAX   PTRATIO         B     LSTAT    target  
0    0.140214  0.982843  0.666608  1.459000  0.441052  1.075562  0.159686  
1    0.557160  0.867883  0.987329  0.303094  0.441052  0.492439  0.101524  
2    0.557160  0.867883  0.987329  0.303094  0.396427  1.208727  1.324247  
3    1.077737  0.752922  1.106115  0.113032  0.416163  1.361517  1.182758  
4    1.077737  0.752922  1.106115  0.113032  0.441052  1.026501  1.487503  
..        ...       ...       ...       ...       ...       ...       ...  
501  0.625796  0.982843  0.803212  1.176466  0.387217  0.418147  0.014454  
502  0.716639  0.982843  0.803212  1.176466  0.441052  0.500850  0.210362  
503  0.773684  0.982843  0.803212  1.176466  0.441052  0.983048  0.148802  
504  0.668437  0.982843  0.803212  1.176466  0.403225  0.865302  0.057989  
505  0.613246  0.982843  0.803212  1.176466  0.441052  0.669058  1.157248  

[506 rows x 14 columns]

In [7]:
thresold=3
print(np.where(z>3))

(array([ 55,  56,  57, 102, 141, 142, 152, 154, 155, 160, 162, 163, 199,
       200, 201, 202, 203, 204, 208, 209, 210, 211, 212, 216, 218, 219,
       220, 221, 222, 225, 234, 236, 256, 257, 262, 269, 273, 274, 276,
       277, 282, 283, 283, 284, 347, 351, 352, 353, 353, 354, 355, 356,
       357, 358, 363, 364, 364, 365, 367, 369, 370, 372, 373, 374, 374,
       380, 398, 404, 405, 406, 410, 410, 411, 412, 412, 414, 414, 415,
       416, 418, 418, 419, 423, 424, 425, 426, 427, 427, 429, 431, 436,
       437, 438, 445, 450, 454, 455, 456, 457, 466], dtype=int64), array([ 1,  1,  1, 11, 12,  3,  3,  3,  3,  3,  3,  3,  1,  1,  1,  1,  1,
        1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  5,  3,  3,  1,  5,
        5,  3,  3,  3,  3,  3,  3,  1,  3,  1,  1,  7,  7,  1,  7,  7,  7,
        3,  3,  3,  3,  3,  5,  5,  5,  3,  3,  3, 12,  5, 12,  0,  0,  0,
        0,  5,  0, 11, 11, 11, 12,  0, 12, 11, 11,  0, 11, 11, 11, 11, 11,
       11,  0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11

In [8]:
bos_new=bs[(z<3).all(axis=1)]
bos_new

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[415 rows x 14 columns]

In [9]:
bs=bos_new
bs

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[415 rows x 14 columns]

# Scaling Techniques

Standard Scaling

In [10]:
x=bs.iloc[:,0:-1]
y=bs.iloc[:,-1]
print (x,y)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       1

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
st=StandardScaler()
x_new=st.fit_transform(x)
x_new

array([[-0.50009668,  0.42727822, -1.25466328, ..., -1.48379449,
         0.43991388, -1.1282211 ],
       [-0.49580542, -0.48858069, -0.55367539, ..., -0.312853  ,
         0.43991388, -0.48493501],
       [-0.49580951, -0.48858069, -0.55367539, ..., -0.312853  ,
         0.36091635, -1.27512537],
       ...,
       [-0.4889668 , -0.48858069,  0.16203913, ...,  1.18595212,
         0.43991388, -1.02616129],
       [-0.47898384, -0.48858069,  0.16203913, ...,  1.18595212,
         0.37295037, -0.89626698],
       [-0.49169611, -0.48858069,  0.16203913, ...,  1.18595212,
         0.43991388, -0.67977647]])

In [13]:
xf=pd.DataFrame(x_new)
xf

0         1         2    3         4         5         6   \
0   -0.500097  0.427278 -1.254663  0.0 -0.083120  0.503296 -0.077906   
1   -0.495805 -0.488581 -0.553675  0.0 -0.708718  0.251194  0.410713   
2   -0.495810 -0.488581 -0.553675  0.0 -0.708718  1.501880 -0.224135   
3   -0.494771 -0.488581 -1.273808  0.0 -0.808451  1.195757 -0.769819   
4   -0.487272 -0.488581 -1.273808  0.0 -0.808451  1.439673 -0.470228   
..        ...       ...       ...  ...       ...       ...       ...   
410 -0.488584 -0.488581  0.162039  0.0  0.234212  0.532762  0.061190   
411 -0.492134 -0.488581  0.162039  0.0  0.234212 -0.241550  0.332249   
412 -0.488967 -0.488581  0.162039  0.0  0.234212  1.159742  0.842267   
413 -0.478984 -0.488581  0.162039  0.0  0.234212  0.861804  0.781636   
414 -0.491696 -0.488581  0.162039  0.0  0.234212 -0.388882  0.478478   

           7         8         9         10        11        12  
0    0.120954 -0.938612 -0.607776 -1.483794  0.439914 -1.128221  
1    0.567909 -0.816465 -0.943176 -0.312853  0.439914 -0.484935  
2    0.567909 -0.816465 -0.943176 -0.312853  0.360916 -1.275125  
3    1.125951 -0.694319 -1.067398  0.108686  0.395854 -1.443679  
4    1.125951 -0.694319 -1.067398  0.108686  0.439914 -1.074098  
..        ...       ...       ...       ...       ...       ...  
410 -0.700185 -0.938612 -0.750631  1.185952  0.344612 -0.402978  
411 -0.797567 -0.938612 -0.750631  1.185952  0.439914 -0.494213  
412 -0.858716 -0.938612 -0.750631  1.185952  0.439914 -1.026161  
413 -0.745895 -0.938612 -0.750631  1.185952  0.372950 -0.896267  
414 -0.686733 -0.938612 -0.750631  1.185952  0.439914 -0.679776  

[415 rows x 13 columns]

In [14]:
x_new.mean()

1.90970707479545e-16

In [15]:
x_new.std()

0.9607689228305228

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split


In [17]:
x_new_train,x_new_test,y_train,y_test=train_test_split(x_new,y,test_size=.20,random_state=42)

In [18]:
x_new_train.shape

(332, 13)

In [19]:
x_new_test.shape

(83, 13)

In [20]:
lm=LinearRegression()
predlm=lm.fit(x_new_train,y_train)
print ('Model Score: ', lm.score(x_new_train,y_train))

Model Score:  0.7361459356698856


In [21]:
predvalue=lm.predict(x_new_test)

print ('Predict Value:', predvalue)
print ('Actual Value:', y_test)

Predict Value: [21.57232667 17.6362508  31.85666169 20.15756668 17.55556597 21.62694593
 15.44994397 26.40717013 30.93242501 12.29913087 20.20812143 12.82083376
 16.4808748  24.57449855 28.14151115  9.35672713 27.65936406 27.75315863
 24.75400459 18.5530135  20.99403702 19.11903542 24.31503995 11.50017769
 22.89552437 22.50642045 34.15908636 28.27226729 25.60910234 24.64451781
 31.59901463 11.81482421 12.3755016  25.04030607 15.837895   14.19625565
 25.94799649 22.93616312 16.02813229 19.32213031 17.33687589 19.38384046
 21.47870187 29.85328776 18.1399087  28.59176675 19.54363538 20.17186346
 20.11096075 24.18397546 22.34838736 22.21694566 37.33389995 13.78748433
 19.61158411 22.94659441 18.47746185 39.0259803  22.18167987 19.01394126
 26.30013722 20.01920153 25.37087482 28.59851918 11.03073401  2.78793965
 32.73238086 20.0483118  16.17685098 20.87210503 35.69165233 20.08201529
 25.64530528 26.0796245  16.7426794  24.84213811 15.71412762 17.14316964
 21.51342814 10.03553729 17.96055483

In [22]:
print ('Error:')
print ('Mean Absolute Error:', mean_absolute_error(y_test,predvalue))
print ('Mean Squared Error:', mean_squared_error(y_test,predvalue))
print ('Root Mean Squared Error:',np.sqrt(mean_squared_error(y_test,predvalue)))

Error:
Mean Absolute Error: 2.4944873675762644
Mean Squared Error: 10.621445730673097
Root Mean Squared Error: 3.2590559569717574


In [23]:
from sklearn.metrics import r2_score

In [24]:
print (r2_score(y_test,predvalue))

0.7761172997388444


MinMax Scaling

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
st=MinMaxScaler()
minmaxx=st.fit_transform(x)
minmaxx

array([[0.00000000e+00, 2.25000000e-01, 6.78152493e-02, ...,
        3.13953488e-01, 1.00000000e+00, 1.07402512e-01],
       [7.32648551e-04, 0.00000000e+00, 2.42302053e-01, ...,
        6.04651163e-01, 1.00000000e+00, 2.44877726e-01],
       [7.31950458e-04, 0.00000000e+00, 2.42302053e-01, ...,
        6.04651163e-01, 9.87015473e-01, 7.60079313e-02],
       ...,
       [1.90020901e-03, 0.00000000e+00, 4.20454545e-01, ...,
        9.76744186e-01, 1.00000000e+00, 1.29213483e-01],
       [3.60460295e-03, 0.00000000e+00, 4.20454545e-01, ...,
        9.76744186e-01, 9.88993460e-01, 1.56972902e-01],
       [1.43423197e-03, 0.00000000e+00, 4.20454545e-01, ...,
        9.76744186e-01, 1.00000000e+00, 2.03238599e-01]])

In [27]:
xm=pd.DataFrame(minmaxx)
xm

0      1         2    3         4         5         6         7   \
0    0.000000  0.225  0.067815  0.0  0.314815  0.556059  0.641607  0.362674   
1    0.000733  0.000  0.242302  0.0  0.172840  0.517259  0.782698  0.471579   
2    0.000732  0.000  0.242302  0.0  0.172840  0.709751  0.599382  0.471579   
3    0.000909  0.000  0.063050  0.0  0.150206  0.662635  0.441813  0.607552   
4    0.002190  0.000  0.063050  0.0  0.150206  0.700176  0.528321  0.607552   
..        ...    ...       ...  ...       ...       ...       ...       ...   
410  0.001965  0.000  0.420455  0.0  0.386831  0.560595  0.681771  0.162594   
411  0.001360  0.000  0.420455  0.0  0.386831  0.441421  0.760041  0.138866   
412  0.001900  0.000  0.420455  0.0  0.386831  0.657092  0.907312  0.123966   
413  0.003605  0.000  0.420455  0.0  0.386831  0.611237  0.889804  0.151456   
414  0.001434  0.000  0.420455  0.0  0.386831  0.418745  0.802266  0.165872   

           8         9         10        11        12  
0    0.000000  0.206501  0.313953  1.000000  0.107403  
1    0.043478  0.103250  0.604651  1.000000  0.244878  
2    0.043478  0.103250  0.604651  0.987015  0.076008  
3    0.086957  0.065010  0.709302  0.992758  0.039987  
4    0.086957  0.065010  0.709302  1.000000  0.118969  
..        ...       ...       ...       ...       ...  
410  0.000000  0.162524  0.976744  0.984336  0.262393  
411  0.000000  0.162524  0.976744  1.000000  0.242895  
412  0.000000  0.162524  0.976744  1.000000  0.129213  
413  0.000000  0.162524  0.976744  0.988993  0.156973  
414  0.000000  0.162524  0.976744  1.000000  0.203239  

[415 rows x 13 columns]

In [28]:
minmaxx_train,minmaxx_test,y_train,y_test=train_test_split(minmaxx,y,test_size=.20,random_state=42)

In [29]:
minmaxx_train.shape

(332, 13)

In [30]:
minmaxx_test.shape

(83, 13)

In [31]:
lm=LinearRegression()
predlm=lm.fit(minmaxx_train,y_train)
print ('Model Score: ', lm.score(minmaxx_train,y_train))


Model Score:  0.7361459356698856


# ENSEMBLE METHODS

In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.datasets import load_iris



In [33]:
iris=load_iris()
x=iris.data
y=iris.target

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=42)

# BAGGING

RANDOM FOREST CLASSIFIER

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf= RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print (accuracy_score(y_test,predrf))
print (confusion_matrix(y_test,predrf))
print (classification_report(y_test,predrf))


1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



EXTRA TREE CLASSIFIER

In [37]:
from sklearn.ensemble import ExtraTreesClassifier

In [38]:
ex=ExtraTreesClassifier(n_estimators=100)
ex.fit(x_train,y_train)
predex=ex.predict(x_test)
print (accuracy_score(y_test,predex))
print (confusion_matrix(y_test,predex))
print (classification_report(y_test,predex))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# BOOSTING

In [39]:
from sklearn.ensemble import AdaBoostClassifier

In [40]:
ad=AdaBoostClassifier()
ad.fit(x_train,y_train)
predad=ad.predict(x_test)
print (accuracy_score(y_test,predad))
print (confusion_matrix(y_test,predad))
print (classification_report(y_test,predad))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [42]:
from sklearn.ensemble import GradientBoostingClassifier

In [44]:
gd=GradientBoostingClassifier()
gd.fit(x_train,y_train)
predgd=gd.predict(x_test)
print (accuracy_score(y_test,predgd))
print (confusion_matrix(y_test,predgd))
print (classification_report(y_test,predgd))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# VOTING CLASSIFIER

In [48]:
from sklearn.ensemble import VotingClassifier

estimator=[]
estimator.append(('knn',KNeighborsClassifier()))
estimator.append(('svc',SVC()))
estimator.append(('dtc',DecisionTreeClassifier()))

In [47]:
estimator

[('knn', KNeighborsClassifier()),
 ('svc', SVC()),
 ('dtc', DecisionTreeClassifier())]

In [54]:
vot_hard=VotingClassifier(estimators=estimator, voting='hard')
vot_hard.fit(x_train,y_train)
y_pred=vot_hard.predict(x_test)
print (y_pred)
print ('Accuracy Score:',accuracy_score(y_test,y_pred))

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy Score: 1.0
